services:
  postgres:
    image: postgres:latest
    container_name: BackCompuMovil
    env_file:
      - .env
    volumes:
      - data_back:/var/lib/postgresql/data
  springboot-app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MAVEN_PROFILE=prod
    ports:
      - "8080:8080"
    depends_on:
      - postgres
volumes:
  data_back: